import type { INestApplication } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import session from 'express-session';
import passport from 'passport';
import type { EnvConfig } from '../config/env.validation';
import { PrismaService } from '../database/prisma.service';

/**
 * Registers session and Passport middleware for cookie-backed authentication.
 *
 * The session cookie is HTTP-only, uses the configured secret, and is marked
 * secure when the API runs with NODE_ENV set to production.
 *
 * @param app - Nest application receiving session and Passport middleware.
 * @param configService - Validated configuration provider for session settings.
 */
export function configureSessionAuth(
  app: INestApplication,
  configService: ConfigService<EnvConfig>,
): void {
  const nodeEnv = configService.get<string>(
    'NODE_ENV',
    process.env.NODE_ENV ?? 'development',
  );
  const isProduction = nodeEnv === 'production';
  const store = createSessionStore(app, configService, isProduction);

  if (isProduction) {
    app.getHttpAdapter().getInstance().set('trust proxy', 1);
  }

  app.use(
    session({
      name: 'linia.sid',
      secret: configService.getOrThrow<string>('SESSION_SECRET'),
      proxy: isProduction,
      resave: false,
      saveUninitialized: false,
      cookie: {
        httpOnly: true,
        sameSite: 'lax',
        secure: isProduction,
        maxAge: 1000 * 60 * 60 * 8,
      },
      ...(store ? { store } : {}),
    }),
  );
  app.use(passport.initialize());
  app.use(passport.session());
}

/**
 * Creates the configured express-session store for the current environment.
 *
 * @param app - Nest application used to resolve PrismaService when needed.
 * @param configService - ConfigService containing session-store settings.
 * @param isProduction - Whether production-only session constraints apply.
 * @returns A PostgreSQL-backed session store, or undefined for local memory sessions.
 * @throws Error when production is configured without a persistent store.
 */
function createSessionStore(
  app: INestApplication,
  configService: ConfigService<EnvConfig>,
  isProduction: boolean,
): session.Store | undefined {
  const driver = configService.get<EnvConfig['SESSION_STORE_DRIVER']>(
    'SESSION_STORE_DRIVER',
    'memory',
  );

  if (driver === 'postgres') {
    return new PrismaSessionStore(app.get(PrismaService));
  }

  if (isProduction) {
    throw new Error('Production requires SESSION_STORE_DRIVER=postgres');
  }

  return undefined;
}

/**
 * Minimal express-session store backed by the application PostgreSQL database.
 *
 * The table is created lazily so local migrations stay focused on domain data,
 * while production can still persist sessions across API restarts. SQL is kept
 * constrained to fixed statements with bound values for session identifiers/data.
 */
class PrismaSessionStore extends session.Store {
  private ready: Promise<void> | null = null;

  constructor(private readonly prisma: PrismaService) {
    super();
  }

  /**
   * Loads unexpired session data for express-session.
   *
   * @param sid - Session identifier from the cookie.
   * @param callback - express-session callback that receives the stored payload or null.
   */
  override get(
    sid: string,
    callback: (err: unknown, session?: session.SessionData | null) => void,
  ): void {
    void this.ensureReady()
      .then(() =>
        this.prisma.$queryRawUnsafe<{ sess: session.SessionData }[]>(
          'SELECT sess FROM linia_sessions WHERE sid = $1 AND expire > NOW()',
          sid,
        ),
      )
      .then((sessions) => callback(null, sessions[0]?.sess ?? null))
      .catch((error: unknown) => callback(error));
  }

  /**
   * Inserts or updates serialized session data with the cookie expiry timestamp.
   *
   * @param sid - Session identifier generated by express-session.
   * @param sessionData - Serializable session payload and cookie metadata.
   * @param callback - Optional express-session completion callback.
   */
  override set(
    sid: string,
    sessionData: session.SessionData,
    callback?: (err?: unknown) => void,
  ): void {
    void this.ensureReady()
      .then(() =>
        this.prisma.$executeRawUnsafe(
          `INSERT INTO linia_sessions (sid, sess, expire)
           VALUES ($1, $2, $3)
           ON CONFLICT (sid)
           DO UPDATE SET sess = EXCLUDED.sess, expire = EXCLUDED.expire`,
          sid,
          JSON.stringify(sessionData),
          this.getExpiry(sessionData),
        ),
      )
      .then(() => callback?.())
      .catch((error: unknown) => callback?.(error));
  }

  /**
   * Deletes the session row during logout or session invalidation.
   *
   * @param sid - Session identifier to delete.
   * @param callback - Optional express-session completion callback.
   */
  override destroy(sid: string, callback?: (err?: unknown) => void): void {
    void this.ensureReady()
      .then(() =>
        this.prisma.$executeRawUnsafe(
          'DELETE FROM linia_sessions WHERE sid = $1',
          sid,
        ),
      )
      .then(() => callback?.())
      .catch((error: unknown) => callback?.(error));
  }

  /**
   * Extends the expiry for active sessions without rewriting the whole payload.
   *
   * @param sid - Session identifier to refresh.
   * @param sessionData - Session payload containing the current cookie expiry.
   * @param callback - Optional express-session completion callback.
   */
  override touch(
    sid: string,
    sessionData: session.SessionData,
    callback?: (err?: unknown) => void,
  ): void {
    void this.ensureReady()
      .then(() =>
        this.prisma.$executeRawUnsafe(
          'UPDATE linia_sessions SET expire = $2 WHERE sid = $1',
          sid,
          this.getExpiry(sessionData),
        ),
      )
      .then(() => callback?.())
      .catch((error: unknown) => callback?.(error));
  }

  /**
   * Ensures the backing table exists once per process before store operations.
   *
   * @returns Shared readiness promise for this store instance.
   */
  private ensureReady(): Promise<void> {
    this.ready ??= this.ensureTable();
    return this.ready;
  }

  /**
   * Creates the session table and expiry index used by express-session.
   *
   * @returns Resolves once table and index creation statements have completed.
   */
  private async ensureTable(): Promise<void> {
    await this.prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS linia_sessions (
        sid varchar PRIMARY KEY,
        sess json NOT NULL,
        expire timestamptz NOT NULL
      )
    `);
    await this.prisma.$executeRawUnsafe(
      'CREATE INDEX IF NOT EXISTS linia_sessions_expire_idx ON linia_sessions (expire)',
    );
  }

  /**
   * Resolves the expiry date from the session cookie or the default eight-hour TTL.
   *
   * @param sessionData - Session payload containing cookie metadata.
   * @returns Expiry timestamp for the session row.
   */
  private getExpiry(sessionData: session.SessionData): Date {
    const cookie = sessionData.cookie;
    const expires = cookie.expires;

    if (expires) {
      return new Date(expires);
    }

    return new Date(Date.now() + (cookie.maxAge ?? 1000 * 60 * 60 * 8));
  }
}
