export enum TaskStatus {
  BLOCKED = 'BLOCKED',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AuditAction {
  RUN_CREATED = 'RUN_CREATED',
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_FAILED = 'TASK_FAILED',
  EVIDENCE_ADDED = 'EVIDENCE_ADDED',
  TASK_UNLOCKED = 'TASK_UNLOCKED',
}
