export enum RunTaskStatus {
  BLOCKED = "BLOCKED",
  READY = "READY",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum RunStatus {
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  ABORTED = "ABORTED",
}

export enum AuditEventType {
  RUN_LAUNCHED = "RUN_LAUNCHED",
  TASK_READY = "TASK_READY",
  TASK_STARTED = "TASK_STARTED",
  TASK_COMPLETED = "TASK_COMPLETED",
  TASK_FAILED = "TASK_FAILED",
  EVIDENCE_ADDED = "EVIDENCE_ADDED",
  RUN_COMPLETED = "RUN_COMPLETED",
  RUN_ABORTED = "RUN_ABORTED",
}

export { RunTaskStatus as TaskStatus, AuditEventType as AuditAction };
